The following config section is found in the SSL server{} block 
	client_max_body_size 4K;
        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;
	server_name example.com; # managed by Certbot

        location / {
                 proxy_pass http://unix:/run/gunicorn.sock;
                 proxy_set_header Host example.com;
        }
        location /robots.txt {
                 root /var/www/html;
        }
        location /assets {
                 root /var/www/html;
        }
